// Procedural pixel-art texture generator.
// Everything here is drawn from scratch on <canvas> — no copyrighted
// Minecraft texture files are used. The look is inspired by the classic
// blocky/pixelated style, but every pixel is generated by this code.

const Textures = (() => {
  // Raw <canvas> elements are cached by name so they can be redrawn into
  // other canvases (for isometric compositing); the base64 URLs used by
  // <img>/CSS are cached separately and derived from those canvases.
  const canvasCache = new Map();
  const urlCache = new Map();

  function hash(x, y, seed) {
    const s = Math.sin(x * 12.9898 + y * 78.233 + seed * 37.719) * 43758.5453;
    return s - Math.floor(s);
  }

  function newCanvas(w, h = w) {
    const c = document.createElement("canvas");
    c.width = w;
    c.height = h;
    return c;
  }

  function getURL(name, canvas) {
    if (urlCache.has(name)) return urlCache.get(name);
    const url = canvas.toDataURL("image/png");
    urlCache.set(name, url);
    return url;
  }

  function getCanvas(name) {
    return canvasCache.get(name);
  }

  // Speckled block texture (grass, dirt, farmland, water, wood...)
  function noiseTile(name, size, base, variants, seed, density = 0.4) {
    if (canvasCache.has(name)) return getURL(name, canvasCache.get(name));
    const c = newCanvas(size);
    const ctx = c.getContext("2d");
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        // pick variant based on hash thresholds
        const h = hash(x, y, seed);
        let picked = null;
        let cum = 0;
        if (h < density) {
          const hh = h / density; // renormalize 0..1
          for (const v of variants) {
            cum += v.chance;
            if (hh < cum) {
              picked = v.color;
              break;
            }
          }
        }
        ctx.fillStyle = picked || base;
        ctx.fillRect(x, y, 1, 1);
      }
    }
    canvasCache.set(name, c);
    return getURL(name, c);
  }

  // Draw explicit pixel grid from row-strings. '.' = transparent.
  function sprite(name, rows, palette, size = 16) {
    if (canvasCache.has(name)) return getURL(name, canvasCache.get(name));
    const c = newCanvas(size);
    const ctx = c.getContext("2d");
    for (let y = 0; y < rows.length; y++) {
      const row = rows[y];
      for (let x = 0; x < row.length; x++) {
        const ch = row[x];
        if (ch === "." || ch === " ") continue;
        ctx.fillStyle = palette[ch] || "#ff00ff";
        ctx.fillRect(x, y, 1, 1);
      }
    }
    canvasCache.set(name, c);
    return getURL(name, c);
  }

  // Darken (or lighten) a fully-opaque source canvas via multiply blend —
  // used to fake left/right cube-face lighting from a single side texture.
  function shade(canvas, factor) {
    const c = newCanvas(canvas.width, canvas.height);
    const ctx = c.getContext("2d");
    ctx.drawImage(canvas, 0, 0);
    ctx.globalCompositeOperation = "multiply";
    const v = Math.round(255 * factor);
    ctx.fillStyle = `rgb(${v},${v},${v})`;
    ctx.fillRect(0, 0, c.width, c.height);
    ctx.globalCompositeOperation = "source-over";
    return c;
  }

  // Composite a flat top texture + a flat side texture into a classic
  // 2:1 isometric cube (top rhombus + shaded left/right faces), using an
  // affine transform to map the square source textures onto the
  // parallelogram faces. This is what gives every ground tile its 3D look.
  function isoCube(name, topName, sideName, opts = {}) {
    if (canvasCache.has(name)) return getURL(name, canvasCache.get(name));
    const top = getCanvas(topName);
    const sideBase = getCanvas(sideName);
    const left = shade(sideBase, opts.dark ?? 0.55);
    const right = shade(sideBase, opts.light ?? 0.78);
    const N = top.width;
    const H = sideBase.height;
    const out = newCanvas(N * 2, N + H);
    const ctx = out.getContext("2d");

    ctx.save();
    ctx.setTransform(1, 0.5, -1, 0.5, N, 0);
    ctx.drawImage(top, 0, 0);
    ctx.restore();

    ctx.save();
    ctx.setTransform(1, 0.5, 0, 1, 0, N / 2);
    ctx.drawImage(left, 0, 0);
    ctx.restore();

    ctx.save();
    ctx.setTransform(1, -0.5, 0, 1, N, N);
    ctx.drawImage(right, 0, 0);
    ctx.restore();

    canvasCache.set(name, out);
    return getURL(name, out);
  }

  // ---- Ground / block tiles (16x16, tileable) ----

  function grass() {
    return noiseTile(
      "grass",
      16,
      "#5c9c3f",
      [
        { color: "#6bad4d", chance: 0.5 },
        { color: "#4f8a35", chance: 0.5 },
      ],
      1.7,
      0.45
    );
  }

  function dirt() {
    return noiseTile(
      "dirt",
      16,
      "#8a5a34",
      [
        { color: "#7a4c29", chance: 0.5 },
        { color: "#9a6a3e", chance: 0.5 },
      ],
      3.3,
      0.4
    );
  }

  function farmland(wet) {
    const name = wet ? "farmland_wet" : "farmland_dry";
    if (canvasCache.has(name)) return getURL(name, canvasCache.get(name));
    const size = 16;
    const c = newCanvas(size);
    const ctx = c.getContext("2d");
    const base = wet ? "#4a3117" : "#7a5230";
    const furrow = wet ? "#33210f" : "#5c3d1e";
    const speck = wet ? "#5a3d1d" : "#8a5f39";
    ctx.fillStyle = base;
    ctx.fillRect(0, 0, size, size);
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const h = hash(x, y, wet ? 9.1 : 4.4);
        if (y % 4 === 1 || y % 4 === 2) {
          ctx.fillStyle = furrow;
          ctx.fillRect(x, y, 1, 1);
        } else if (h < 0.2) {
          ctx.fillStyle = speck;
          ctx.fillRect(x, y, 1, 1);
        }
      }
    }
    canvasCache.set(name, c);
    return getURL(name, c);
  }

  function water() {
    if (canvasCache.has("water")) return getURL("water", canvasCache.get("water"));
    const size = 16;
    const c = newCanvas(size);
    const ctx = c.getContext("2d");
    ctx.fillStyle = "#3465c9";
    ctx.fillRect(0, 0, size, size);
    for (let y = 0; y < size; y++) {
      for (let x = 0; x < size; x++) {
        const h = hash(x, y, 6.6);
        if (h < 0.12) {
          ctx.fillStyle = "#5588e0";
          ctx.fillRect(x, y, 1, 1);
        } else if (h > 0.94) {
          ctx.fillStyle = "#254d9e";
          ctx.fillRect(x, y, 1, 1);
        }
      }
    }
    canvasCache.set("water", c);
    return getURL("water", c);
  }

  function grassSide() {
    const name = "grass_side";
    if (canvasCache.has(name)) return getURL(name, canvasCache.get(name));
    dirt();
    const c = newCanvas(16);
    const ctx = c.getContext("2d");
    ctx.drawImage(getCanvas("dirt"), 0, 0);
    for (let x = 0; x < 16; x++) {
      const h = hash(x, 0, 22.3);
      const fringe = h < 0.5 ? 2 : 3;
      ctx.fillStyle = h < 0.33 ? "#5c9c3f" : h < 0.66 ? "#6bad4d" : "#4f8a35";
      ctx.fillRect(x, 0, 1, fringe);
    }
    canvasCache.set(name, c);
    return getURL(name, c);
  }

  // ---- Isometric cube tiles (top + shaded left/right side faces) ----

  function isoGrass() {
    grass();
    grassSide();
    return isoCube("iso_grass", "grass", "grass_side");
  }

  function isoFarmland(wet) {
    farmland(wet);
    dirt();
    return isoCube(wet ? "iso_farmland_wet" : "iso_farmland_dry", wet ? "farmland_wet" : "farmland_dry", "dirt");
  }

  function isoWater() {
    water();
    return isoCube("iso_water", "water", "water", { dark: 0.5, light: 0.72 });
  }

  function plank() {
    return noiseTile(
      "plank",
      16,
      "#8a6239",
      [
        { color: "#7a5430", chance: 0.6 },
        { color: "#96703f", chance: 0.4 },
      ],
      8.2,
      0.3
    );
  }

  function stonePath() {
    return noiseTile(
      "stonepath",
      16,
      "#9a9a92",
      [
        { color: "#87877e", chance: 0.5 },
        { color: "#aaaaa0", chance: 0.5 },
      ],
      12.1,
      0.35
    );
  }

  // ---- Crop growth stages ----
  // Blades are drawn as solid vertical strokes growing from the soil line
  // (row 15) upward, rather than hand-placed dots, so they read as plants
  // instead of a checkerboard.
  function cropCanvas(key, draw) {
    if (canvasCache.has(key)) return getURL(key, canvasCache.get(key));
    const c = newCanvas(16);
    const ctx = c.getContext("2d");
    draw(ctx);
    canvasCache.set(key, c);
    return getURL(key, c);
  }

  function drawBlade(ctx, x, height, color, soilY = 15) {
    ctx.fillStyle = color;
    for (let i = 0; i < height; i++) {
      ctx.fillRect(x, soilY - i, 1, 1);
    }
  }

  function wheat(stage) {
    return cropCanvas(`wheat${stage}`, (ctx) => {
      if (stage === 0) {
        ctx.fillStyle = "#5f9a34";
        ctx.fillRect(7, 14, 1, 2);
        ctx.fillRect(8, 15, 1, 1);
        return;
      }
      const xs = [3, 5, 7, 9, 11, 13];
      const heightSets = [null, [3, 4, 3, 5, 3, 4], [7, 8, 7, 9, 7, 8], [11, 12, 11, 13, 11, 12]];
      const heights = heightSets[stage];
      const stemColor = stage === 3 ? "#c9a23a" : stage === 2 ? "#6fa63d" : "#5f9a34";
      xs.forEach((x, i) => drawBlade(ctx, x, heights[i], stemColor));
      if (stage === 3) {
        // golden grain heads on top of each blade
        const headColors = ["#e8d968", "#d9c34a"];
        xs.forEach((x, i) => {
          const topY = 15 - heights[i];
          ctx.fillStyle = headColors[i % 2];
          ctx.fillRect(x - 1, topY, 1, 2);
          ctx.fillRect(x + 1, topY, 1, 2);
          ctx.fillStyle = "#b8892f";
          ctx.fillRect(x, topY - 1, 1, 1);
        });
      } else if (stage === 2) {
        xs.forEach((x, i) => {
          const topY = 15 - heights[i];
          ctx.fillStyle = "#8db84a";
          ctx.fillRect(x - 1, topY + 1, 1, 1);
          ctx.fillRect(x + 1, topY + 1, 1, 1);
        });
      }
    });
  }

  function leafyTop(ctx, stage, opts = {}) {
    // Shared sprout/leaf silhouette used by carrot & potato (stages 0-2).
    const xs = [5, 7, 9, 11];
    const heightSets = [
      [0, 0, 0, 0],
      [2, 3, 3, 2],
      [5, 6, 6, 5],
    ];
    const heights = heightSets[stage] || heightSets[2];
    const color = opts.color || "#4a9a34";
    if (stage === 0) {
      ctx.fillStyle = color;
      ctx.fillRect(7, 15, 1, 1);
      ctx.fillRect(8, 15, 1, 1);
      return;
    }
    xs.forEach((x, i) => drawBlade(ctx, x, heights[i], color));
  }

  function carrot(stage) {
    return cropCanvas(`carrot${stage}`, (ctx) => {
      leafyTop(ctx, stage, { color: "#3f9a3f" });
      if (stage === 3) {
        // orange carrot root peeking out of the soil
        ctx.fillStyle = "#e07a1f";
        ctx.fillRect(7, 12, 3, 3);
        ctx.fillRect(8, 15, 1, 1);
        ctx.fillStyle = "#f0972f";
        ctx.fillRect(7, 12, 1, 2);
      }
    });
  }

  function potato(stage) {
    return cropCanvas(`potato${stage}`, (ctx) => {
      leafyTop(ctx, stage, { color: "#3f8a2a" });
      if (stage === 3) {
        ctx.fillStyle = "#c9a24a";
        ctx.fillRect(6, 13, 2, 2);
        ctx.fillRect(9, 12, 2, 2);
        ctx.fillStyle = "#8a6a2f";
        ctx.fillRect(6, 14, 1, 1);
        ctx.fillRect(10, 13, 1, 1);
        // small white flowers, like ripe Minecraft potato plants
        ctx.fillStyle = "#f2f2ea";
        ctx.fillRect(5, 6, 1, 1);
        ctx.fillRect(10, 5, 1, 1);
      }
    });
  }

  // ---- Animals (simple flat pixel icons) ----
  function sheep() {
    const P = { w: "#f5f5f0", W: "#d9d9d0", d: "#3a3a3a", p: "#5a4636", n: "#e8cba8" };
    const rows = [
      "................",
      "................",
      "...WWWWWWWW.....",
      "..WwwwwwwwwW....",
      "..WwwwwwwwwW....",
      ".WwwwwwwwwwwW...",
      ".Wwwwwwwwwwww...",
      "nnWwwwwwwwwW....",
      "nnn.WWWWWW......",
      "pp...pp...pp....",
      "pp...pp...pp....",
      "dd...dd...dd....",
      "................",
      "................",
      "................",
      "................",
    ];
    return sprite("sheep", rows, P);
  }

  function cow() {
    const P = { w: "#efe6d8", b: "#8a5a3a", B: "#6b4126", d: "#2a2a2a", n: "#e8b98f" };
    const rows = [
      "................",
      "................",
      "..bb........bb..",
      ".bwwbbbbbbbbwwb.",
      ".bwwwbb..bbwwwb.",
      ".wwwwwwwwwwwwww.",
      ".wwbbwwwwwwbbww.",
      ".wwwwwwwwwwwwww.",
      "..nnwwwwwwwwnn..",
      "..bb..wwww..bb..",
      "..bb........bb..",
      "..dd........dd..",
      "................",
      "................",
      "................",
      "................",
    ];
    return sprite("cow", rows, P);
  }

  function pufferfish() {
    const P = { y: "#d9b25a", Y: "#e8c96f", s: "#a9843f", d: "#241f14", w: "#fbf6e6" };
    const rows = [
      "................",
      "..s...ss...s....",
      ".s.sYYYYYYs...s.",
      "s..YYYYYYYYs....",
      "...YYwwYYYYY.s..",
      "s.YYYwdYYYYYYs..",
      "..YYYYYYYYYYYY..",
      ".YYYYYYYYYYYYYs.",
      "sYYYYYYYYYYYYYY.",
      ".YYYYsYYYYsYYYs.",
      "s.YYYYYYYYYYYY..",
      "..sYYYYYYYYYs.s.",
      "...s.sYYYYs..s..",
      "....s..ss..s....",
      "................",
      "................",
    ];
    return sprite("pufferfish", rows, P);
  }

  // ---- Items / icons ----
  function emerald() {
    const P = { g: "#1fae5a", G: "#3fd67f", d: "#0f6b38", h: "#bdf5d4" };
    const rows = [
      "................",
      "................",
      "......GG........",
      ".....GggGG......",
      "....GggggGG.....",
      "...GggggggGG....",
      "..hgggggggggd...",
      "..hggggggggdd...",
      "..hggggggggdd...",
      "...hgggggggd....",
      "....hgggggd.....",
      ".....hgggd......",
      "......hgd.......",
      ".......d........",
      "................",
      "................",
    ];
    return sprite("emerald", rows, P);
  }

  function wool() {
    const P = { w: "#f5f5f0", W: "#d9d9d0" };
    const rows = [
      "................",
      "....WWWWWW......",
      "...WwwwwwwW.....",
      "..WwwWwwWwwW....",
      "..WwwwwwwwwW....",
      "..WwwWwwWwwW....",
      "...WwwwwwwW.....",
      "....WWWWWW......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ];
    return sprite("wool", rows, P);
  }

  function milk() {
    const P = { m: "#c8ccd0", M: "#e8ecf0", w: "#f5f7fa", d: "#8a8f96" };
    const rows = [
      "................",
      "....MMMMMM......",
      "....M....M......",
      "...MwwwwwwM.....",
      "...MwwwwwwM.....",
      "..MwwwwwwwwM....",
      "..MwwwwwwwwM....",
      "..MwwwwwwwwM....",
      "..MwwwwwwwwM....",
      "..MMMMMMMMMM....",
      "..dddddddddd....",
      "................",
      "................",
      "................",
      "................",
      "................",
    ];
    return sprite("milk", rows, P);
  }

  function seedIcon(kind) {
    if (kind === "wheat") {
      const P = { d: "#c9a24a", D: "#8a6a2f" };
      const rows = [
        "................","................","......D.........","....D.d.D.......",
        "...D.d.d.D......","....d.D.d.......","...D.d.d.D......","....D.d.D.......",
        "...D.d.d.D......","....d.D.d.......","..................","................",
        "................","................","................","................",
      ];
      return sprite("seed_wheat", rows, P);
    }
    if (kind === "carrot") return carrot(3);
    return potato(3);
  }

  function fishItem() {
    return pufferfish();
  }

  function lockIcon() {
    const P = { m: "#d8c150", M: "#f0da70", d: "#5a4a10" };
    const rows = [
      "................",
      "................",
      "....mmmmmm......",
      "...m......m.....",
      "...m......m.....",
      "..dMMMMMMMMd....",
      "..dMdddddMMd....",
      "..dMdMMMdMMd....",
      "..dMdddddMMd....",
      "..dMMMMMMMMd....",
      "..dMMMMMMMMd....",
      "...dddddddd.....",
      "................",
      "................",
      "................",
      "................",
    ];
    return sprite("lock", rows, P);
  }

  function signTexture() {
    return plank();
  }

  return {
    grass,
    dirt,
    farmland,
    water,
    plank,
    stonePath,
    isoGrass,
    isoFarmland,
    isoWater,
    wheat,
    carrot,
    potato,
    sheep,
    cow,
    pufferfish,
    emerald,
    wool,
    milk,
    seedIcon,
    fishItem,
    lockIcon,
    signTexture,
  };
})();
